### ISSUE TITLE
🗄️ Development 📌

### ISSUE THREAD

**Issue by EnzoHB** [EnzoHB/Favicon-Manager#1]
# ToDo List
**Everything I plan to do in the future.**

- [ ] **Code :**

  - [ ] **Background :**
    - [ ] **Changing variables name;**
    - [ ] **Create better modules;**
    - [ ] **Cleaning this code because it's a mess;**
    - [ ] **Find a way to solve the Burlador de CSP - Through a TestCSP function?;**
    - [ ] **Figure out How to solve some weird Bug that docs.microsoft has;**
    - [ ] **Finish the Erro handling;**
    - [ ] **Update the URLObject Structure;**
 
  - [ ] **Options Page :**
    - [ ] **Add the "Change State" Feature;**
    - [ ] **Add the Feature that lets you put whatever Image you want as the default one;**
    - [ ] **Add the Feature that lets you put whatever Image you want as the original one;**
    - [ ] **Add the warns when you try to do something that's not allowed;**
    - [ ] **Make the Errors Page - Logs of them and their meaning**
    
  - [ ] **Extension Info :**
    - [ ] **Improve the Data Structure;**

- [ ] **Design :**

    - [ ] **Clean CSS because It's a mess too;**
    - [ ] **Design a better UI for both the Popup and Options Page;**

# Status

**Current working on: Code > Background > Change Variables Name;**

**url -> fullURL
**requiredURL -> mainURL**
**mainURL -> shortedURL**
**original -> default**
****
****
****
